### ISSUE TITLE
NextInputs的Comparator有溢出报错。

### ISSUE THREAD

**Issue by doubledouble** [yoojia/NextInputs#2]
private static final Comparator<Scheme> ORDERING = new Comparator<Scheme>() {
        @Override
        public int compare(Scheme lhs, Scheme rhs) {
            return lhs.orderPriority - rhs.orderPriority;
        }
    };

lz自己的TestOrderTest没跑过吗。。 Integer.MAX_VALUE溢出了 测试用例不通过

**Comment by yoojia** [comment]
@doubledouble 

我这里的测试用例运行正常。可以提供一下出错信息吗？
