### ISSUE TITLE
inputs.test() 返回值问题？

### ISSUE THREAD

**Issue by CCC2016** [yoojia/NextInputs#3]
`inputs.add(Provider.fromString("")).with(StaticScheme.ChineseIDCard());`

当验证的值为空时是否应该返回 false？

使用的是安卓平台。

**Comment by yoojia** [comment]
Android的可以使用 [https://github.com/yoojia/NextInputs-Android](https://github.com/yoojia/NextInputs-Android) 这个项目。我看了你前一个Issue了，估计你是使用Provider.fromString("")直接把值传进去，这样的值是固定不变的，所以会出现第一次校验是正确，后面就不正确了。你需要使用Loader来动态获取值。
